
package com.cdcoding.model


enum class Chain(val string: String) {
	Bitcoin("bitcoin"),
	Litecoin("litecoin"),
	Ethereum("ethereum"),
	SmartChain("smartchain"),
	Solana("solana"),
	Polygon("polygon"),
	Thorchain("thorchain"),
	Cosmos("cosmos"),
	Osmosis("osmosis"),
	Arbitrum("arbitrum"),
	Ton("ton"),
	Tron("tron"),
	Doge("doge"),
	Optimism("optimism"),
	Aptos("aptos"),
	Base("base"),
	AvalancheC("avalanchec"),
	Sui("sui"),
	Xrp("xrp"),
	OpBNB("opbnb"),
	Fantom("fantom"),
	Gnosis("gnosis"),
	Celestia("celestia"),
	Injective("injective"),
	Sei("sei"),
	Manta("manta"),
	Blast("blast"),
	Noble("noble"),
	ZkSync("zksync"),
	Linea("linea"),
	Mantle("mantle"),
	Celo("celo"),
	Near("near"),
}

